version: '3.7'

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password

  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['./symfony/:/var/www/symfony:cached']

  phpmyadmin:
    image: phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
